### PR TITLE
V1.9.2.2

### PR DESCRIPTION
**Pull request by notimplementedyet**

### CODE REVIEW

**Comment by colinmollenhour** [comment]
Hi Fernando, I did some rebasing of your work on the latest master and got what looks to be a pretty good result. Please let me know if you approve before I make it master. I kept your name/email as the author of the commits I rebased.

https://github.com/colinmollenhour/magento-lite/commits/notimplementedyet-v1922

**Comment by notimplementedyet** [comment]
Hi Colin, i'm about to review and test your merge. I will let you know if everything is fine, stay tuned ;)

**Comment by notimplementedyet** [comment]
Hi Colin, looks good to me except "app\etc\modules\Cm_RedisSession.xml" and "includes\config.php" are missing (intentional?) and the rwd theme could be cleaned up.

**Comment by colinmollenhour** [comment]
Great, thanks for the review. I added the Cm_RedisSession file (it is ignored by .gitignore so I didn't notice that it wasn't added to git). If I remember correctly the includes/config.php file is also generated by Mage_Compiler so I think it is better not to add this file to the repo so that it doesn't appear as a modified file.

**Comment by colinmollenhour** [comment]
I've merged the rebased branch into master. Thanks again for your work in getting this updated!

**Pull request closed without merging**
